language: cpp
compiler:
  - gcc

os:
  - linux

cache:
  directories:
    - tools/build/bin
    - third_party/opencv_install

env:
  global:
    - QTDIR=/opt/qt58
  matrix:
    - CONFIG=debug
    - CONFIG=release

dist: trusty
sudo: required
addons:
  apt:
    sources:
      # - llvm-toolchain-trusty
      - ubuntu-toolchain-r-test
      - sourceline: 'ppa:beineri/opt-qt58-trusty'
      - sourceline: 'ppa:mc3man/trusty-media'
    packages:
      # - clang-3.8
      # - clang-format-3.8
      # - llvm-3.8-dev
      # - libc++-dev
      - libudev-dev
      - libav-tools
      - libavcodec-dev
      - libavdevice-dev
      - libavfilter-dev
      - libavformat-dev
      - libavresample-dev
      - libavutil-dev
      - qt58-meta-full

git:
  # Handled in ar-build
  submodules: false

before_install:

before_script:
  # Prepare environment (pull dependencies, build tools).
  - travis_retry python ar-build setup
  - QT_ENV_SCRIPT=$(find /opt -name 'qt*-env.sh')
  - source $QT_ENV_SCRIPT

script:
  - python ar-build build --config=$CONFIG
